name:                language
version:             0.1.0.0
github:              "lehmacdj/language"
license:             BSD3
author:              "Devin Lehmacher"
maintainer:          "lehmacdj@gmail.com"
copyright:           "Copyright: (c) 2017 Devin Lehmacher"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Miscellaneous

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lehmacdj/language#readme>

dependencies:
- base >= 4.7 && < 5
- bound
- bytestring
- classy-prelude
- containers
- deriving-compat
- lens
- megaparsec
- mtl
- parser-combinators
- text
- unliftio

default-extensions:
- DataKinds
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DeriveFoldable
- FlexibleContexts
- GADTs
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeOperators

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  language-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - language

tests:
  language-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - language
    - tasty
    - tasty-hunit
    - tasty-discover
    - tasty-golden
