name:                language
synopsis:            Devin's language experiments.
version:             0.1.0.0
category:            Language
github:              "lehmacdj/language"
license:             BSD3
author:              "Devin Lehmacher"
maintainer:          "lehmacdj@gmail.com"
copyright:           "(c) 2021 Devin Lehmacher"
extra-source-files:
- README.md
- ChangeLog.md
description:
  Home of my language experiments. Except where otherwise impossible I try to
  implement all features I'm interested in experimenting with in a single
  language. Please see the README on GitHub at
  <https://github.com/lehmacdj/language#readme> for further information.

dependencies:
- base >= 4.7 && < 5
- bound
- bytestring
- classy-prelude
- containers
- deriving-compat
- lens
- megaparsec
- mtl
- parser-combinators
- polysemy
- polysemy-plugin
- polysemy-readline
- prettyprinter
- prettyprinter-ansi-terminal
- text
- unliftio

default-extensions:
- DataKinds
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DeriveFoldable
- FlexibleContexts
- GADTs
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeOperators

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -fplugin=Polysemy.Plugin
- -flate-specialise
- -fspecialise-aggressively

library:
  source-dirs: src

executables:
  language-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - language

tests:
  language-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - language
    - tasty
    - tasty-hunit
    - tasty-discover
    - tasty-golden
    - tasty-quickcheck
    - quickcheck-instances
